defaultPortal: developer-test-account-1
portals:
  - name: developer-test-account-1
    portalId: 242241986
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLLl6pjaMhIaAA0AQAAA4G0DQAJYAgEAAPgAAAAAAAAAAAYYwqPBcyCLn68lKO7pDDIU-GY-mPKOud6d6IDtwpYGQxuWnrU6TwAABEEAAAB4AAAAAAAAAAAAgAAAAAAABAAAwAcAjvAxPGBQBgBEAGBA_BgGABAgAwAAAAAAPP4DAAAAAAAAAAwEAAAAAAAAAAAAABAAAMBCFPqUVWjBMQg8iprY-zwDIPh6WAcaSgNuYTJSAFoAYABoAHAA
        expiresAt: '2025-03-17T07:56:30.806Z'
    accountType: DEVELOPER_TEST
    personalAccessKey: >-
      CiRuYTItNzI5YS0xNGZkLTQ3MWItODBmNy1hMGU5ZWUyYmZiMGQQwqPBcxiLn68lKhkABeaRggvbrdatlRno8SpwL_iyufq9drhsSgNuYTI
    parentAccountId: 242241976
