name: Deploy to HubSpot

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install HubSpot CLI
        run: npm install -g @hubspot/cli

      - name: Create HubSpot Config File
        run: |
          echo "Creating HubSpot config file..."
          cat <<EOF > hubspot.config.yml
          defaultPortal: my-hubspot
          portals:
            - name: my-hubspot
              authType: personalaccesskey
              personalAccessKey: ${{ secrets.HUBSPOT_PERSONAL_ACCESS_KEY }}
              portalId: ${{ secrets.HUBSPOT_ACCOUNT_ID }}
          EOF

      - name: Verify Config File Exists
        run: |
          echo "Checking if hubspot.config.yml exists..."
          ls -la
          cat hubspot.config.yml  # Display the file for debugging

      - name: Upload Theme to HubSpot
        run: hs upload my-website-theme new-website-theme --config hubspot.config.yml
