name: Deploy to HubSpot

on:
  push:
    branches:
      - master  # Change to your main branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install HubSpot CLI
        run: npm install -g @hubspot/cli

      - name: Create HubSpot Config File
        run: |
          echo "defaultPortal: my-hubspot" > hubspot.config.yml
          echo "portals:" >> hubspot.config.yml
          echo "  my-hubspot:" >> hubspot.config.yml
          echo "    authType: personalaccesskey" >> hubspot.config.yml
          echo "    personalAccessKey: ${{ secrets.HUBSPOT_PERSONAL_ACCESS_KEY }}" >> hubspot.config.yml
          echo "    portalId: ${{ secrets.HUBSPOT_ACCOUNT_ID }}" >> hubspot.config.yml

      - name: Verify Config File
        run: cat hubspot.config.yml  # Debugging step

      - name: Upload Theme to HubSpot
        run: hs upload my-website-theme new-website-theme --config hubspot.config.yml
