name: Deploy to HubSpot

on:
  push:
    branches:
      - master  # Change to your main branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install HubSpot CLI
        run: npm install -g @hubspot/cli

      - name: Create HubSpot Config File
        run: |
          mkdir -p ~/.config/hubspot
          echo "defaultPortal: my-hubspot" > ~/.config/hubspot/hubspot.config.yml
          echo "portals:" >> ~/.config/hubspot/hubspot.config.yml
          echo "  my-hubspot:" >> ~/.config/hubspot/hubspot.config.yml
          echo "    authType: personalaccesskey" >> ~/.config/hubspot/hubspot.config.yml
          echo "    personalAccessKey: ${{ secrets.HUBSPOT_ACCESS_TOKEN }}" >> ~/.config/hubspot/hubspot.config.yml
          echo "    portalId: ${{ secrets.HUBSPOT_ACCOUNT_ID }}" >> ~/.config/hubspot/hubspot.config.yml

      - name: Upload Theme to HubSpot
        run: hs upload my-website-theme new-website-theme
