name: Deploy to HubSpot

on:
  push:
    branches:
      - master  # Change to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install HubSpot CLI
        run: npm install -g @hubspot/cli

      - name: Initialize HubSpot CLI
        run: hs init --config hubspot.config.yml --no-interactive

      - name: Configure HubSpot Authentication
        run: |
          cat <<EOF > hubspot.config.yml
          defaultPortal: my-hubspot
          portals:
            my-hubspot:
              authType: personalaccesskey
              personalAccessKey: ${{ secrets.HUBSPOT_ACCESS_TOKEN }}
              portalId: ${{ secrets.HUBSPOT_ACCOUNT_ID }}
          EOF

      - name: Verify Config File
        run: cat hubspot.config.yml  # Debugging step

      - name: Upload Theme to HubSpot
        run: hs upload my-website-theme new-website-theme --config hubspot.config.yml
