on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: HubSpot Deploy Action
        uses: ./
        with:
          src_dir: my-website-theme
          dest_dir: new-website-theme
          account_id: ${{ vars.hubspot_account_id || secrets.hubspot_portal_id }}
          personal_access_key: ${{ secrets.hubspot_personal_access_key }}
